import CourseKit
import Foundation

/// The HTML page a person reviews before a course is merged: route map, charts, checks, and every parameter.
public enum ReviewReport {
    public static func html(for result: BuildResult, inputs: BuildInputs) -> String {
        let config = inputs.config
        let course = result.course
        let total = config.officialDistanceMeters
        let treadmill0 = TreadmillProfile(course: course, segment: course.fullCourseSegment, settings: .pelotonTread)
        let treadmill1 = TreadmillProfile(
            course: course, segment: course.fullCourseSegment, settings: TreadmillSettings(baselinePercent: 1))
        let stats = result.courseFile.stats
        let failing = result.failingSections.count + result.acceptance.filter { !$0.passed }.count

        var html = """
            <!doctype html>
            <html lang="en"><head><meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>\(escape(config.name)) \(escape(config.edition)) — course review</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script>
            <style>
            body { font: 14px/1.45 -apple-system, system-ui, sans-serif; margin: 24px auto; max-width: 1100px; padding: 0 16px; color: #1d1d1f; }
            h1 { margin-bottom: 4px; } h2 { margin-top: 32px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
            .meta { color: #666; } .pass { color: #1a7f37; font-weight: 600; } .fail { color: #c62828; font-weight: 600; }
            table { border-collapse: collapse; width: 100%; margin: 8px 0; } td, th { border-bottom: 1px solid #eee; padding: 4px 8px; text-align: left; vertical-align: top; }
            th { background: #fafafa; } td.num { text-align: right; font-variant-numeric: tabular-nums; }
            #map { height: 520px; border: 1px solid #ddd; border-radius: 6px; background: #f3f3f0; }
            #map .leaflet-tile-pane { filter: grayscale(1) brightness(1.08) contrast(0.85); opacity: 0.55; }
            .km-label { background: #fff; border: 2px solid #d500f9; border-radius: 10px; padding: 0 5px; font: 600 11px/16px system-ui, sans-serif; color: #4a0072; white-space: nowrap; text-align: center; }
            .end-label { background: #212121; color: #fff; border-radius: 10px; padding: 0 6px; font: 700 11px/18px system-ui, sans-serif; white-space: nowrap; text-align: center; }
            #map-note { display: none; background: #fff8e1; border: 1px solid #ffe082; padding: 6px 10px; border-radius: 6px; margin: 8px 0; }
            svg.chart { width: 100%; height: auto; background: #fff; border: 1px solid #eee; border-radius: 6px; }
            .legend span { display: inline-block; margin-right: 16px; } .swatch { display: inline-block; width: 14px; height: 4px; vertical-align: middle; margin-right: 4px; }
            details { margin: 8px 0; }
            </style></head><body>
            <h1>\(escape(config.name)) \(escape(config.edition))</h1>
            <p class="meta">Review report generated by \(CourseBuilder.toolVersion) from <code>CourseData/\(escape(config.id))/</code>. \
            Not committed. \(failing == 0 ? "<span class=\"pass\">All checks pass.</span>" : "<span class=\"fail\">\(failing) check(s) fail.</span>")</p>
            <table>
            <tr><th>Distance</th><td class="num">\(format(total / 1000, "%.3f")) km</td><th>Gain / loss</th><td class="num">\(format(stats.elevationGainMeters, "%.1f")) m / \(format(stats.elevationLossMeters, "%.1f")) m</td></tr>
            <tr><th>Elevation range</th><td class="num">\(format(stats.minimumElevationMeters, "%.1f"))–\(format(stats.maximumElevationMeters, "%.1f")) m</td><th>Incline intervals</th><td class="num">\(result.intervals.count)</td></tr>
            <tr><th>Interpolated spans</th><td class="num">\(result.cleaned.spans.count)</td><th>Steep 10 m steps</th><td class="num">\(result.cleaned.steepSteps.count)</td></tr>
            </table>

            <h2>Checks</h2>
            <table><tr><th></th><th>Check</th><th>Result</th></tr>
            """
        for check in result.acceptance {
            html +=
                "<tr><td class=\"\(check.passed ? "pass" : "fail")\">\(check.passed ? "✓" : "✗")</td>"
                + "<td>\(escape(check.name))</td><td>\(escape(check.detail))</td></tr>\n"
        }
        html += "</table>\n"

        html +=
            "<h2>Route</h2>\n<p id=\"map-note\">Map tiles can't load when this file is opened directly; the route and "
            + "markers are drawn on a plain background. To see the street map, run <code>make course-report ID="
            + escape(config.id) + "</code> and open the URL it prints.</p>\n<div id=\"map\"></div>\n"
        html += """
            <p class="legend"><span><i class="swatch" style="background:#d500f9;height:6px;box-shadow:0 0 0 2px #fff"></i>course (measured, calibrated)</span>\
            <span><i class="swatch" style="background:repeating-linear-gradient(90deg,#888 0 4px,transparent 4px 8px)"></i>router output</span>\
            <span><i class="swatch" style="background:#ff9800;height:6px"></i>bridge / tunnel (elevation interpolated)</span>\
            <span><i class="swatch" style="background:#e53935;height:6px"></i>other interpolated samples</span>\
            <span>● checkpoints: green = calibration anchor, blue = checked only · grey dots: waypoints · labels every 5 km. Toggle layers top right.</span></p>
            """

        html += "<h2>Elevation</h2>\n" + elevationChart(result, total: total)
        html += """
            <p class="legend"><span><i class="swatch" style="background:#bbb"></i>measured</span>\
            <span><i class="swatch" style="background:#ef6c00"></i>cleaned</span>\
            <span><i class="swatch" style="background:#1565c0"></i>smoothed (used)</span>\
            <span><i class="swatch" style="background:#ffcdd2"></i>interpolated span</span></p>
            """
        html +=
            "<h2>Incline</h2>\n" + inclineChart(result, treadmill0: treadmill0, treadmill1: treadmill1, total: total)
        html += """
            <p class="legend"><span><i class="swatch" style="background:#6a1b9a"></i>course incline (signed)</span>\
            <span><i class="swatch" style="background:#2e7d32"></i>Peloton Tread, 0% baseline</span>\
            <span><i class="swatch" style="background:#00897b"></i>Peloton Tread, 1% baseline</span></p>
            """
        html += "<table><tr><th>From km</th><th>To km</th><th>Course</th><th>Tread (0%)</th><th>Tread (1%)</th></tr>\n"
        for interval in result.intervals {
            let mid = (interval.startMeters + interval.endMeters) / 2
            let t0 = treadmill0.intervals.first { $0.startMeters <= mid && mid < $0.endMeters }?.inclinePercent ?? 0
            let t1 = treadmill1.intervals.first { $0.startMeters <= mid && mid < $0.endMeters }?.inclinePercent ?? 0
            html +=
                "<tr><td class=\"num\">\(format(interval.startMeters / 1000, "%.2f"))</td>"
                + "<td class=\"num\">\(format(interval.endMeters / 1000, "%.2f"))</td>"
                + "<td class=\"num\">\(format(interval.inclinePercent, "%+.1f"))%</td>"
                + "<td class=\"num\">\(format(t0, "%.1f"))%</td><td class=\"num\">\(format(t1, "%.1f"))%</td></tr>\n"
        }
        html += "</table>\n"
        html +=
            "<p>Treadmill prompts: \(treadmill0.intervals.count - 1) changes at a 0% baseline, "
            + "\(treadmill1.intervals.count - 1) at a 1% baseline.</p>\n"

        html +=
            "<h2>Distance calibration</h2>\n<p>Traced length of each stretch between checkpoints vs the official "
            + "length. A stretch off by more than \(format(result.maximumSectionErrorMeters, "%.0f")) m fails "
            + "(wrong street). Anchors pin the distance scale.</p>\n"
        html += "<table><tr><th>Stretch</th><th>Official</th><th>Traced</th><th>Error</th><th></th></tr>\n"
        for section in result.sections {
            let bad = abs(section.errorMeters) > result.maximumSectionErrorMeters
            html +=
                "<tr><td>\(escape(section.fromName)) → \(escape(section.toName))</td>"
                + "<td class=\"num\">\(format(section.officialMeters, "%.0f")) m</td>"
                + "<td class=\"num\">\(format(section.rawMeters, "%.0f")) m</td>"
                + "<td class=\"num \(bad ? "fail" : "")\">\(format(section.errorMeters, "%+.0f")) m</td>"
                + "<td>\(bad ? "✗" : "")</td></tr>\n"
        }
        html += "</table>\n<table><tr><th>Checkpoint</th><th>Official km</th><th>Off route</th><th>Anchor</th></tr>\n"
        for point in result.located {
            html +=
                "<tr><td>\(escape(point.checkpoint.name))</td>"
                + "<td class=\"num\">\(format(point.checkpoint.officialMeters / 1000, "%.3f"))</td>"
                + "<td class=\"num\">\(format(point.offRouteMeters, "%.0f")) m</td>"
                + "<td>\(point.checkpoint.anchor ? "yes" : "")</td></tr>\n"
        }
        html +=
            "</table>\n<p>Anchor scale factors (official ÷ traced): "
            + result.calibration.sectionScales.map {
                "\(format($0.fromOfficial / 1000, "%.2f"))–\(format($0.toOfficial / 1000, "%.2f")) km: "
                    + format($0.scale, "%.4f")
            }.joined(separator: "; ") + "</p>\n"

        html +=
            "<h2>Interpolated spans</h2>\n<table><tr><th>From km</th><th>To km</th><th>Length</th><th>Why</th></tr>\n"
        for span in result.cleaned.spans {
            html +=
                "<tr><td class=\"num\">\(format(span.startMeters / 1000, "%.3f"))</td>"
                + "<td class=\"num\">\(format(span.endMeters / 1000, "%.3f"))</td>"
                + "<td class=\"num\">\(format(span.endMeters - span.startMeters, "%.0f")) m</td>"
                + "<td>\(escape(span.reasons.joined(separator: "; ")))</td></tr>\n"
        }
        html += "</table>\n"
        if !result.cleaned.steepSteps.isEmpty {
            html += "<h2>Steep 10 m steps after cleaning</h2>\n<table><tr><th>At km</th><th>Grade</th></tr>\n"
            for step in result.cleaned.steepSteps {
                html +=
                    "<tr><td class=\"num\">\(format(step.atMeters / 1000, "%.3f"))</td>"
                    + "<td class=\"num\">\(format(step.gradePercent, "%+.1f"))%</td></tr>\n"
            }
            html += "</table>\n"
        }

        html += "<h2>Parameters and sources</h2>\n<table>\n"
        for (key, value) in result.courseFile.processing.parameters.sorted(by: { $0.key < $1.key }) {
            html += "<tr><th>\(escape(key))</th><td>\(escape(value))</td></tr>\n"
        }
        html += "<tr><th>Attribution</th><td>\(escape(config.source.attribution ?? ""))</td></tr>\n"
        html += "<tr><th>Notes</th><td>\(escape(config.source.notes ?? ""))</td></tr>\n</table>\n"

        html += mapScript(result, inputs: inputs)
        html += "</body></html>\n"
        return html
    }

    // MARK: - Charts

    private static func elevationChart(_ result: BuildResult, total: Double) -> String {
        let width = 1060.0
        let height = 320.0
        let pad = (left: 44.0, right: 12.0, top: 12.0, bottom: 28.0)
        let measured = result.cleaned.measured.compactMap { $0 }
        let lo = floor(min(measured.min() ?? 0, result.cleaned.cleaned.min() ?? 0) - 1)
        let hi = ceil(max(measured.max() ?? 1, result.cleaned.cleaned.max() ?? 1) + 1)
        func x(_ d: Double) -> Double { pad.left + d / total * (width - pad.left - pad.right) }
        func y(_ e: Double) -> Double { pad.top + (hi - e) / (hi - lo) * (height - pad.top - pad.bottom) }

        var svg =
            "<svg class=\"chart\" viewBox=\"0 0 \(Int(width)) \(Int(height))\" xmlns=\"http://www.w3.org/2000/svg\">\n"
        for span in result.cleaned.spans {
            svg +=
                "<rect x=\"\(f(x(span.startMeters)))\" y=\"\(f(pad.top))\" "
                + "width=\"\(f(max(1, x(span.endMeters) - x(span.startMeters))))\" "
                + "height=\"\(f(height - pad.top - pad.bottom))\" fill=\"#ffcdd2\"/>\n"
        }
        svg += axes(width: width, height: height, pad: pad, total: total, lo: lo, hi: hi, unit: "m", x: x, y: y)
        let d = result.cleaned.distances
        svg += polyline(
            zip(d, result.cleaned.measured).compactMap { distance, e in e.map { (x(distance), y($0)) } }, "#bbb", 1)
        svg += polyline(zip(d, result.cleaned.cleaned).map { (x($0), y($1)) }, "#ef6c00", 1)
        svg += polyline(zip(result.smoothed.distances, result.smoothed.elevations).map { (x($0), y($1)) }, "#1565c0", 2)
        for point in result.located {
            let px = f(x(point.checkpoint.officialMeters))
            svg +=
                "<line x1=\"\(px)\" x2=\"\(px)\" y1=\"\(f(pad.top))\" y2=\"\(f(height - pad.bottom))\" "
                + "stroke=\"\(point.checkpoint.anchor ? "#2e7d32" : "#ef6c00")\" stroke-dasharray=\"2 3\" "
                + "stroke-width=\"0.8\"><title>\(escape(point.checkpoint.name))</title></line>\n"
        }
        return svg + "</svg>\n"
    }

    private static func inclineChart(
        _ result: BuildResult, treadmill0: TreadmillProfile, treadmill1: TreadmillProfile, total: Double
    ) -> String {
        let width = 1060.0
        let height = 240.0
        let pad = (left: 44.0, right: 12.0, top: 12.0, bottom: 28.0)
        let values = result.intervals.map(\.inclinePercent) + treadmill1.intervals.map(\.inclinePercent)
        let lo = min(-1, floor(values.min() ?? 0) - 0.5)
        let hi = max(2, ceil(values.max() ?? 0) + 0.5)
        func x(_ d: Double) -> Double { pad.left + d / total * (width - pad.left - pad.right) }
        func y(_ v: Double) -> Double { pad.top + (hi - v) / (hi - lo) * (height - pad.top - pad.bottom) }
        func steps(_ intervals: [(Double, Double, Double)]) -> [(Double, Double)] {
            intervals.flatMap { [(x($0.0), y($0.2)), (x($0.1), y($0.2))] }
        }
        var svg =
            "<svg class=\"chart\" viewBox=\"0 0 \(Int(width)) \(Int(height))\" xmlns=\"http://www.w3.org/2000/svg\">\n"
        svg += axes(width: width, height: height, pad: pad, total: total, lo: lo, hi: hi, unit: "%", x: x, y: y)
        svg +=
            "<line x1=\"\(f(pad.left))\" x2=\"\(f(width - pad.right))\" y1=\"\(f(y(0)))\" y2=\"\(f(y(0)))\" "
            + "stroke=\"#999\" stroke-width=\"0.8\"/>\n"
        svg += polyline(steps(result.intervals.map { ($0.startMeters, $0.endMeters, $0.inclinePercent) }), "#6a1b9a", 2)
        svg += polyline(
            steps(treadmill0.intervals.map { ($0.startMeters, $0.endMeters, $0.inclinePercent) }), "#2e7d32", 1.5)
        svg += polyline(
            steps(treadmill1.intervals.map { ($0.startMeters, $0.endMeters, $0.inclinePercent) }), "#00897b", 1.5,
            dash: "5 3")
        return svg + "</svg>\n"
    }

    private static func axes(
        width: Double, height: Double, pad: (left: Double, right: Double, top: Double, bottom: Double), total: Double,
        lo: Double, hi: Double, unit: String, x: (Double) -> Double, y: (Double) -> Double
    ) -> String {
        var svg = ""
        let stepY = niceStep((hi - lo) / 5)
        var v = (lo / stepY).rounded(.up) * stepY
        while v <= hi {
            svg +=
                "<line x1=\"\(f(pad.left))\" x2=\"\(f(width - pad.right))\" y1=\"\(f(y(v)))\" y2=\"\(f(y(v)))\" "
                + "stroke=\"#f0f0f0\"/><text x=\"\(f(pad.left - 6))\" y=\"\(f(y(v) + 4))\" font-size=\"11\" "
                + "text-anchor=\"end\" fill=\"#666\">\(format(v == 0 ? 0 : v, "%g"))\(unit)</text>\n"
            v += stepY
        }
        var km = 0.0
        while km * 1000 <= total {
            svg +=
                "<text x=\"\(f(x(km * 1000)))\" y=\"\(f(height - 8))\" font-size=\"11\" text-anchor=\"middle\" "
                + "fill=\"#666\">\(format(km, "%g")) km</text>\n"
            km += 5
        }
        return svg
    }

    private static func niceStep(_ raw: Double) -> Double {
        let magnitude = pow(10, floor(log10(max(raw, 1e-9))))
        for factor in [1.0, 2, 5, 10] where factor * magnitude >= raw { return factor * magnitude }
        return 10 * magnitude
    }

    private static func polyline(_ points: [(Double, Double)], _ color: String, _ width: Double, dash: String? = nil)
        -> String
    {
        let list = points.map { "\(f($0.0)),\(f($0.1))" }.joined(separator: " ")
        let dashAttribute = dash.map { " stroke-dasharray=\"\($0)\"" } ?? ""
        return
            "<polyline points=\"\(list)\" fill=\"none\" stroke=\"\(color)\" stroke-width=\"\(width)\"\(dashAttribute)/>\n"
    }

    // MARK: - Map

    private static func mapScript(_ result: BuildResult, inputs: BuildInputs) -> String {
        func json(_ coordinates: [Coordinate]) -> String {
            "[" + coordinates.map { "[\(f($0.latitude, 6)),\(f($0.longitude, 6))]" }.joined(separator: ",") + "]"
        }
        let samples = result.allSamples
        let course = Array(samples.prefix(result.cleaned.distances.count))

        // Runs of interpolated samples, split into structures (bridges, tunnels) and everything else.
        let reasons = result.cleaned.reasons
        func runs(where matches: (SuspectReason) -> Bool) -> [String] {
            var result: [String] = []
            var run: [Coordinate] = []
            for (index, reason) in reasons.enumerated() {
                if let reason, matches(reason) {
                    run.append(course[index].location)
                } else if !run.isEmpty {
                    result.append(json(run.count == 1 ? [run[0], run[0]] : run))
                    run = []
                }
            }
            if !run.isEmpty { result.append(json(run)) }
            return result
        }
        let structureRuns = runs { if case .structure = $0 { true } else { false } }
        let otherRuns = runs { if case .structure = $0 { false } else { true } }

        // Labels every 5 km, at halfway, and at the finish, placed at the calibrated distance.
        let distances = result.cleaned.distances
        let total = inputs.config.officialDistanceMeters
        var marks = Array(stride(from: 5000.0, to: total - 1000, by: 5000)).map { ($0, "\(Int($0 / 1000)) km") }
        if total > 30_000 { marks.append((total / 2, String(format: "½ %.1f", total / 2000))) }
        let labels = marks.compactMap { mark -> String? in
            guard let index = distances.firstIndex(where: { $0 >= mark.0 }) else { return nil }
            let c = course[index].location
            return "[\(f(c.latitude, 6)),\(f(c.longitude, 6)),\(jsString(mark.1))]"
        }.joined(separator: ",")
        let start = course.first!.location
        let finish = course.last!.location

        let checkpoints = result.located.map { point in
            "[\(f(point.checkpoint.location.latitude, 6)),\(f(point.checkpoint.location.longitude, 6)),"
                + "\(point.checkpoint.anchor),"
                + jsString(point.checkpoint.name + " (km " + format(point.checkpoint.officialMeters / 1000, "%g") + ")")
                + "]"
        }.joined(separator: ",")
        let waypoints = inputs.waypoints.map {
            "[\(f($0.location.latitude, 6)),\(f($0.location.longitude, 6)),\(jsString($0.name))]"
        }.joined(separator: ",")
        return """
            <script>
            const note = () => { document.getElementById('map-note').style.display = 'block'; };
            if (typeof L === 'undefined') {
              note();
              document.getElementById('map').textContent = 'The map library could not load (offline?).';
              throw new Error('Leaflet unavailable');
            }
            const map = L.map('map');
            // OSM's tile policy requires a Referer, which browsers don't send for file:// pages; serve the report
            // over http (make course-report) to see tiles. Without them, the overlays still draw.
            if (location.protocol === 'file:') note();
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom: 19,
              referrerPolicy: 'strict-origin-when-cross-origin',
              attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'})
              .on('tileerror', note).addTo(map);
            const raw = L.polyline(\(json(inputs.route)), {color: '#888', weight: 1.5, dashArray: '4 4'});
            const structures = L.layerGroup([\(structureRuns.joined(separator: ","))]
              .map(r => L.polyline(r, {color: '#ff9800', weight: 10, opacity: 0.9})));
            const other = L.layerGroup([\(otherRuns.joined(separator: ","))]
              .map(r => L.polyline(r, {color: '#e53935', weight: 10, opacity: 0.9})));
            const routeLine = \(json(course.map(\.location)));
            L.polyline(routeLine, {color: '#fff', weight: 11, opacity: 1}).addTo(map);
            const route = L.polyline(routeLine, {color: '#d500f9', weight: 6, opacity: 1}).addTo(map);
            structures.addTo(map);
            other.addTo(map);
            const waypoints = L.layerGroup([\(waypoints)].map(w =>
              L.circleMarker([w[0], w[1]], {radius: 3, color: '#555', weight: 1, fillOpacity: 0.8}).bindTooltip(w[2])));
            const checkpoints = L.layerGroup([\(checkpoints)].map(c =>
              L.circleMarker([c[0], c[1]], {radius: 7, color: c[2] ? '#2e7d32' : '#1e88e5', weight: 2, fillOpacity: 0.85})
                .bindTooltip(c[3]))).addTo(map);
            const labels = L.layerGroup([\(labels)].map(k => L.marker([k[0], k[1]], {interactive: false,
              icon: L.divIcon({className: 'km-label', html: k[2], iconSize: null})}))).addTo(map);
            L.marker([\(f(start.latitude, 6)), \(f(start.longitude, 6))], {icon: L.divIcon({className: 'end-label', html: 'START', iconSize: null})}).addTo(map);
            L.marker([\(f(finish.latitude, 6)), \(f(finish.longitude, 6))], {icon: L.divIcon({className: 'end-label', html: 'FINISH', iconSize: null})}).addTo(map);
            L.control.layers(null, {
              'Router output (raw line)': raw, 'Waypoints': waypoints, 'Checkpoints': checkpoints,
              'Bridges & tunnels': structures, 'Other interpolated samples': other, 'km labels': labels,
            }, {collapsed: false}).addTo(map);
            map.fitBounds(route.getBounds());
            </script>

            """
    }

    // MARK: - Formatting

    private static func f(_ value: Double, _ places: Int = 1) -> String { String(format: "%.\(places)f", value) }

    private static func format(_ value: Double, _ pattern: String) -> String { String(format: pattern, value) }

    private static func escape(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;").replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;").replacingOccurrences(of: "\"", with: "&quot;")
    }

    private static func jsString(_ text: String) -> String {
        let data = try? JSONEncoder().encode(text)
        return data.flatMap { String(data: $0, encoding: .utf8) } ?? "\"\""
    }
}
